### ISSUE TITLE
use id instead of name to identify collection

### ISSUE THREAD

**Issue by pvgenuchten** [geonetwork/geonetwork-microservices#33]
/ogcapi/collections returns collections with a name parameter having the identifier.

![image](https://user-images.githubusercontent.com/299829/107833154-a670df80-6d92-11eb-9ac8-776a0ca08247.png)

The spec however indicates to use 'id' as identifier
https://docs.opengeospatial.org/DRAFTS/20-004.html#collections-metadata

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/109168101-c636d900-777e-11eb-8856-fa0c0e085047.png)
