### ISSUE TITLE
No mapping found for [title] in order to sort on

### ISSUE THREAD

**Issue by pvgenuchten** [geonetwork/geonetwork-microservices#40]
The specification has an unconventional approach to sorting:

- ?sortby=title and ?sortby=+title sort ascending (+ in url's is however decoded as " ", so i'd suggest to skip this case, using %2B would be the alternative, but not friendly)
- ?sortby=-title sorts descending

current use of sortby throws:
```
No mapping found for [title] in order to sort on
```
e.g. which fields are currently available for sorting?

see also:
https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/parameters/sortby.yaml
https://github.com/opengeospatial/ogcapi-records/blob/master/core/standard/clause_9_sorting.adoc

**Comment by fxprunayre** [comment]
> e.g. which fields are currently available for sorting?

https://apps.titellus.net/ogcapi/collections/main/sortables

**Comment by fxprunayre** [comment]
> BTW we have to update to old encoding `title:desc` to `-title`

Done.

**Comment by fxprunayre** [comment]
> Also sortBy is a list so not sure if .../collections/mycat/items?...&sortby=-updated,recordId&... should be .../collections/mycat/items?...&sortby=-updated&sortby=recordId&... ?

Added.

`%2B` or `+` works fine.

**Comment by pvgenuchten** [comment]
Great!
