### ISSUE TITLE
Dockerfile of gn-cloud-ogc-api-records-service?

### ISSUE THREAD

**Issue by wagner-intevation** [geonetwork/geonetwork-microservices#94]
Hi,

I'm wondering how [geonetwork/gn-cloud-ogc-api-records-service](https://hub.docker.com/r/geonetwork/gn-cloud-ogc-api-records-service) is built, as the [layers](https://hub.docker.com/layers/geonetwork/gn-cloud-ogc-api-records-service/4.2.5-1/images/sha256-a397ce1806bfe4f5ec6dd0aa02175d594145428f02a5f58df88be82d93f992ed?context=explore) have no command information and this repository, especially the path `modules/services/ogc-api-records` contains no Dockerfile either. Where does that image come from?

**Comment by pmauduit** [comment]
Also the yaml snippet being used for the CI which publishes the image on docker hub is here:
https://github.com/geonetwork/geonetwork-microservices/blob/main/.github/workflows/ci.yaml#L25-L28

**Comment by wagner-intevation** [comment]
Thank you very much for the super quick answer, I will have a look at the references.
